# Generated by Django 3.1.7 on 2021-02-20 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skiing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name="skiresort",
            name="tags",
            field=models.ManyToManyField(to="skiing.Tag"),
        ),
    ]
