# Generated by Django 3.1.7 on 2021-02-26 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skiing", "0002_auto_20210220_1439"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_professional_skier",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="partnered_ski_resorts",
            field=models.ManyToManyField(to="skiing.SkiResort"),
        ),
        migrations.CreateModel(
            name="SkiLift",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                (
                    "ski_resort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="skiing.skiresort",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
