# Generated by Django 3.1.7 on 2021-03-03 11:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skiing", "0003_auto_20210226_1644"),
    ]

    operations = [
        migrations.CreateModel(
            name="SkiLiftLimits",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_status",
                    models.CharField(
                        choices=[
                            ("DEF", "Normal Skier"),
                            ("PRO", "Professional Skier"),
                        ],
                        default="DEF",
                        max_length=3,
                        unique=True,
                    ),
                ),
                ("daily_limit", models.IntegerField()),
                ("monthly_limit", models.IntegerField()),
                ("days_in_row_limit", models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name="skilift",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_professional_skier",
            field=models.BooleanField(default=False),
        ),
    ]
