# Generated by Django 3.1.7 on 2021-03-03 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("skiing", "0004_auto_20210303_1236"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SkiLiftLimits",
            new_name="SkiLiftLimit",
        ),
    ]
