# Generated by Django 3.1.7 on 2021-03-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skiing", "0009_auto_20210303_1306"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="ski_lift_uses_in_row",
            field=models.IntegerField(default=0),
        ),
    ]
