# Generated by Django 3.1.7 on 2021-03-04 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skiing", "0010_user_ski_lift_uses_in_row"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="ski_lift_uses_in_row",
        ),
        migrations.AddField(
            model_name="skiliftlimit",
            name="weekend_limit",
            field=models.IntegerField(default=0),
        ),
    ]
